---

- name: Run Command on Windows
  hosts: all
  tasks:
    - name: Run whomi
      ansible.windows.win_command: whoami
      register: whoami_out

    - name: Print return information from the previous task
      ansible.builtin.debug:
        stdout: "{{ whoami_out }}"
