
---

- name: Create folder
  hosts: all
  tasks:
    - name: Set variable
      set_fact:
        exam_path: C:\Temp\Exams\{{USERNAME}}
    - set_fact:
        exam_file: "{{ exam_path }}\\README.txt"

    - name: Create  directory structure
      win_file:
        path: "{{ exam_path }}"
        state: directory

    - name: Create README file
      win_file:
        path: "{{ exam_file }}"
        state: touch

    - name: Add Content to Readme file
      win_lineinfile:
        path: "{{ exam_file }}"
        line: Hello {{ USERNAME }} !
        state: present

    - name: Set the right permission for user
      win_acl:
        user: "{{ USERNAME }}"
        path: "{{ exam_file }}"
        type: allow
        rights: Write
